In [34]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [35]:
# Q1.number of records
df = pd.read_csv('laptops.csv')
df.shape

(2160, 12)

In [36]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [37]:
# Q2.number of brands
df['Brand'].nunique()

27

In [38]:
# Q3.missing values
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [39]:
df.loc[(df['Brand'] == 'Dell'), 'Model'].unique()

array(['Vostro', 'Latitude', 'XPS', 'Precision'], dtype=object)

In [40]:
# Q4.maximum final price of Dell notebooks
df.loc[(df['Brand'] == 'Dell') & (df['Model'] == 'Notebook'), 'Final Price'].max()

nan

In [41]:
df.loc[(df['Brand'] == 'Dell') , 'Final Price'].max()

np.float64(3936.0)

In [42]:
#Q6.median value
df['Screen'].median()

np.float64(15.6)

In [43]:
most_freq_value = df['Screen'].mode()[0]
most_freq_value

np.float64(15.6)

In [44]:
df.fillna({'Screen':most_freq_value}, inplace=True)

In [45]:
df['Screen'].isna().sum()

np.int64(0)

In [46]:
df['Screen'].median()

np.float64(15.6)

In [48]:
# Q7. calculate weights
X = df.loc[df['Brand'] == 'Innjoo', ['RAM', 'Storage', 'Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [51]:
XTX = X.T@X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [52]:
XTX_ = np.linalg.inv(XTX)
XTX_

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [56]:
y = [1100, 1300, 800, 900, 1000, 1100]
w = XTX_ @ X.T
print(w)
res = w @ y
res

[[ 0.26298349 -0.12560233 -0.40646389  0.14958687  0.05244042  0.05244042]
 [-0.00110155  0.00295059  0.00125892 -0.00177691 -0.00076387 -0.00076387]
 [-0.08772226  0.0269791   0.17140891 -0.0302108  -0.00153546 -0.00153546]]


array([45.58076606,  0.42783519, 45.29127938])

In [54]:
sum(res)

np.float64(91.2998806299555)